# For more information see:
# https://thegraybook.vvvv.org/reference/extending/publishing.html

name: push_nuget

# on push on main
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@master
#      with:
#        submodules: 'true'
#        lfs: 'true'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v2.0.0

    - name: Publish VL Nuget
      uses: vvvv/PublishVLNuget@1.0.43
      with:
        csproj: src\VL.Devices.Axis.csproj

        nuget-key: ${{ secrets.VVVV_ORG_NUGET_KEY }}
